server:
  port: 3306

spring:
  datasource:
    url: jdbc:mysql://srv960.hstgr.io/u938606973_Femenino2106
    username: u938606973_Femenino2106
    password: Femenino2106
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 2
      maxLifetime: 1800000
      autoCommit: true
