server:
  port: 3306

spring:
  datasource:
    url: jdbc:mysql://srv958.hstgr.io/u938606973_Ciudadela5
    username: u938606973_Ciudadela5
    password: 3174843970aB1+X
    hikari:
      connectionTimeout: 40000
      maximumPoolSize: 10
      maxLifetime: 600000        # 10 minutos (menor que el timeout de la BD)
      idleTimeout: 300000        # 5 minutos de inactividad antes de cerrar conexiones
      keepaliveTime: 300000      # Mantiene vivas las conexiones cada 5 minutos
      autoCommit: true
