server:
  port: 3306

spring:
  datasource:
    url: jdbc:mysql://sql805.main-hosting.eu/u938606973_Ciudadela5
    username: u938606973_Ciudadela5
    password: Ciudadela5+
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 2
      maxLifetime: 1800000
      autoCommit: true
