server:
  port: 3306

spring:
  datasource:
    url: jdbc:mysql://sql141.main-hosting.eu/u938606973_palcos
    username: u938606973_palcos
    password: 3174843970aB+
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 2
      maxLifetime: 1800000
      autoCommit: true
