server:
  port: 3306

spring:
  datasource:
    url: jdbc:mysql://srv958.hstgr.io/u938606973_runcentro
    username: u938606973_runcentro
    password: 3174843970aB1+
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 2
      maxLifetime: 1800000
      autoCommit: true
