server:
  port: 3306

spring:
  datasource:
    url: jdbc:mysql://sql718.main-hosting.eu/u650745231_clusterbd
    username: u650745231_clusteruser
    password: Cluster2022+
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 2
      maxLifetime: 1800000
      autoCommit: true
