server:
  port: 3306

spring:
  datasource:
    url: jdbc:mysql://srv958.hstgr.io/u938606973_Ciu_09_02_2025
    username: u938606973_Ciu_09_02_2025
    password: 3174843970aB1+X
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 2
      maxLifetime: 1800000
      autoCommit: true
