server:
  port: 3306

spring:
  datasource:
    url: jdbc:mysql:sql555.main-hosting.eu
    username: u239297815_ccd
    password: 3174843970aB+
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 2
      maxLifetime: 1800000
      autoCommit: true
