server:
  port: 3306

spring:
  datasource:
    url: jdbc:mysql://sql141.main-hosting.eu/u938606973_CCDBD
    username: u938606973_CCDBD
    password: CaliCiudadDeportiva2023+
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 2
      maxLifetime: 1800000
      autoCommit: true
