server:
  port: 3306

spring:
  datasource:
    url: jdbc:mysql://srv958.hstgr.io/u938606973_crocs_06_2025
    username: u938606973_crocs_06_2025
    password: 3174843970aB1+A
    hikari:
      connectionTimeout: 10000         # 10 segundos para obtener una conexión
      maximumPoolSize: 5
      maxLifetime: 15000               # 15 segundos (menos que wait_timeout)
      idleTimeout: 10000               # 10 segundos
      keepaliveTime: 10000             # 10 segundos para mantenerla viva
      autoCommit: true
